/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.netsoft.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-16-2007
 * 
 * XDoclet definition:
 * @struts.form name="roleForm"
 */
public class RoleForm extends ActionForm {
	/*
	 * Generated Methods
	 */

    private Integer id;
    private String rname;
    private Integer rdelStyle;
    private String rmessage;
    private Integer[] rmidptables1;
    private Integer[] rmidptables2;
    private Integer[] rmidptables3;
    private Integer[] rmidptables4;
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRdelStyle() {
		return rdelStyle;
	}

	public void setRdelStyle(Integer rdelStyle) {
		this.rdelStyle = rdelStyle;
	}

	public String getRmessage() {
		return rmessage;
	}

	public void setRmessage(String rmessage) {
		this.rmessage = rmessage;
	}

	public String getRname() {
		return rname;
	}

	public void setRname(String rname) {
		this.rname = rname;
	}

	public Integer[] getRmidptables1() {
		return rmidptables1;
	}

	public void setRmidptables1(Integer[] rmidptables1) {
		this.rmidptables1 = rmidptables1;
	}

	public Integer[] getRmidptables2() {
		return rmidptables2;
	}

	public void setRmidptables2(Integer[] rmidptables2) {
		this.rmidptables2 = rmidptables2;
	}

	public Integer[] getRmidptables3() {
		return rmidptables3;
	}

	public void setRmidptables3(Integer[] rmidptables3) {
		this.rmidptables3 = rmidptables3;
	}

	public Integer[] getRmidptables4() {
		return rmidptables4;
	}

	public void setRmidptables4(Integer[] rmidptables4) {
		this.rmidptables4 = rmidptables4;
	}
}