/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.netsoft.web.struts.form;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.netsoft.dao.pojos.Employye;
import com.netsoft.services.intf.IEmployeeServices;
import com.netsoft.util.ConsoleDate;

/** 
 * MyEclipse Struts
 * Creation date: 01-14-2007
 * 
 * XDoclet definition:
 * @struts.form name="employeeForm"
 */
public class EmployeeForm extends ActionForm {
	private Integer id;
    private Integer depts;
    private String deptsName;
    private String eaccount;
    private String ename;
    private String epwd;
    private Integer esex;
    private String ebirthday;
    private String ehandTel;
    private String ecode;
    private Integer edelStyle;
    private Integer login;
    private Integer toId;//失效用户信息转移时，转移给谁了
    private Integer emidrs[];
    private String open;//是否公开
    
	public Integer getDepts() {
		return depts;
	}

	public void setDepts(Integer depts) {
		this.depts = depts;
	}

	public String getDeptsName() {
		return deptsName;
	}

	public void setDeptsName(String deptsName) {
		this.deptsName = deptsName;
	}

	public String getEaccount() {
		return eaccount;
	}

	public void setEaccount(String eaccount) {
		this.eaccount = eaccount;
	}

	public String getEbirthday() {
		return ebirthday;
	}

	public void setEbirthday(String ebirthday) {
		this.ebirthday = ebirthday;
	}

	public String getEcode() {
		return ecode;
	}

	public void setEcode(String ecode) {
		this.ecode = ecode;
	}

	public Integer getEdelStyle() {
		return edelStyle;
	}

	public void setEdelStyle(Integer edelStyle) {
		this.edelStyle = edelStyle;
	}

	public String getEhandTel() {
		return ehandTel;
	}

	public void setEhandTel(String ehandTel) {
		this.ehandTel = ehandTel;
	}

	public String getEname() {
		return ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getEpwd() {
		return epwd;
	}

	public void setEpwd(String epwd) {
		this.epwd = epwd;
	}

	public Integer getEsex() {
		return esex;
	}

	public void setEsex(Integer esex) {
		this.esex = esex;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getLogin() {
		return login;
	}

	public void setLogin(Integer login) {
		this.login = login;
	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	  
	}

	public Integer[] getEmidrs() {
		return emidrs;
	}

	public void setEmidrs(Integer[] emidrs) {
		this.emidrs = emidrs;
	}

	public Integer getToId() {
		return toId;
	}

	public void setToId(Integer toId) {
		this.toId = toId;
	}

	public String getOpen() {
		return open;
	}

	public void setOpen(String open) {
		this.open = open;
	}
}