/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.netsoft.web.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.beans.BeanUtils;

import com.netsoft.dao.beans.DeptsBean;
import com.netsoft.services.intf.IDeptsServices;
import com.netsoft.services.intf.IEmployeeServices;
import com.netsoft.util.CheckUser;
import com.netsoft.web.struts.form.DeptForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-15-2007
 * 
 * XDoclet definition:
 * @struts.action path="/dept" name="deptForm" input="/form/dept.jsp" parameter="method" scope="request" validate="true"
 */
public class DeptAction extends DispatchAction {

	public IDeptsServices ids;
	public ActionForward addDepts(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(!CheckUser.checkSession(request, response))
		{
			return mapping.findForward(CheckUser.JUMP_URL);
		}
		DeptForm df=(DeptForm) form;
		DeptsBean db=new DeptsBean();
		BeanUtils.copyProperties(df,db);
		ids.addDepts(db);
		return mapping.findForward("deptsView");
	}
	
	public ActionForward deptsView(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(!CheckUser.checkSession(request, response))
		{
			return mapping.findForward(CheckUser.JUMP_URL);
		}
		List list=ids.getAllDepts();
		request.setAttribute("deptList",list);
		return mapping.findForward("deptsViewPage");
	}
	
	public ActionForward modiView(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(!CheckUser.checkSession(request, response))
		{
			return mapping.findForward(CheckUser.JUMP_URL);
		}
		String id=request.getParameter("id");
		DeptsBean db=ids.getDeptsById(Integer.parseInt(id));
		request.setAttribute("db",db);
		return mapping.findForward("addDeptsView");
	}
	
	public ActionForward modiDept(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(!CheckUser.checkSession(request, response))
		{
			return mapping.findForward(CheckUser.JUMP_URL);
		}
		DeptForm df=(DeptForm) form;
		DeptsBean db=new DeptsBean();
		BeanUtils.copyProperties(df,db);
		ids.updateDepts(db);
		return mapping.findForward("deptsView");
	}
	public IDeptsServices getIds() {
		return ids;
	}
	public void setIds(IDeptsServices ids) {
		this.ids = ids;
	}
}