/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.netsoft.web.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.netsoft.dao.pojos.Employye;

/** 
 * MyEclipse Struts
 * Creation date: 01-15-2007
 * 
 * XDoclet definition:
 * @struts.form name="deptForm"
 */
public class DeptForm extends ActionForm {

	 private Integer id;
     private Integer employye;
     private String dname;
     private String employyeName;
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public String getDname() {
		return dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public String getEmployyeName() {
		return employyeName;
	}

	public void setEmployyeName(String employyeName) {
		this.employyeName = employyeName;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
}

	public Integer getEmployye() {
		return employye;
	}

	public void setEmployye(Integer employye) {
		this.employye = employye;
	}
}